apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-rakeshgarg-master
  namespace: kubernetes-cluster-rakeshgarg
  labels:
    app: dotnet-app-rakeshgarg
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app-rakeshgarg
  template:
    metadata:
      labels:
        app: dotnet-app-rakeshgarg
    spec:
      containers:
        - name: dotnet-app-rakeshgarg
          image: rakeshgarg2021/app_rakeshgarg:i-rakeshgarg-master-latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-rakeshgarg
  namespace: kubernetes-cluster-rakeshgarg
spec:
  type: NodePort
  selector: 
    app: dotnet-app-rakeshgarg
  ports:    
  - protocol: TCP
    nodePort: 30157
    port: 80
    targetPort: 80